[package]
name = "midi_router"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
env_logger = "0.11.5"
jack = "0.13.0"
lazy_static = "1.5.0"
log = "0.4.22"
regex = "1.11.0"
strum_macros = "0.26.4"
tempfile = "3.14.0"
